
java_binary (
    name = "review1",
    visibility = ["//visibility:public"],
    srcs = [
        "Review1.java",
    ],
    main_class = "com.example.reviews.Review1",
    tags = ["MacAndCheese"],
    deps = [
        "//src/main/java/com/example/customers:amir",
    ],

)