java_library(
    name = "macAndCheese",
    srcs = ["macAndCheese.java"],
    deps = [
        "//ingredients:cheese",
        "//ingredients:macaroni",
    ],
)

java_library(
    name = "pizza",
    srcs = ["Pizza.java"],
    deps = [
        "//ingredients:cheese",
        "//ingredients:dough",
        "//ingredients:tomato",
    ],
)